package fr.dreamin.dreamapi.api.item;

public enum ItemAction {
  RIGHT_CLICK,
  RIGHT_CLICK_AIR,
  RIGHT_CLICK_BLOCK,
  RIGHT_CLICK_ENTITY,

  SHIFT_RIGHT_CLICK,
  SHIFT_RIGHT_CLICK_AIR,
  SHIFT_RIGHT_CLICK_BLOCK,
  SHIFT_RIGHT_CLICK_ENTITY,

  LEFT_CLICK,
  LEFT_CLICK_AIR,
  LEFT_CLICK_BLOCK,
  LEFT_CLICK_ENTITY,

  SHIFT_LEFT_CLICK,
  SHIFT_LEFT_CLICK_AIR,
  SHIFT_LEFT_CLICK_BLOCK,
  SHIFT_LEFT_CLICK_ENTITY,

  DROP,
  SWAP,
  SHIFT_SWAP,
  PICKUP,
  HELD,
  UNHELD,
  INTERACT_ENTITY,
  SET_ARMOR,
  REMOVE_ARMOR,
  ATTACK,

  INTERACT_MODEL_ENGINE,
  ATTACK_MODEL_ENGINE,

  EAT,
  CONSUME,
  CHAT_SEND;
}