package fr.dreamin.example.cmd;

import cloud.commandframework.annotations.CommandDescription;
import cloud.commandframework.annotations.CommandMethod;
import cloud.commandframework.annotations.CommandPermission;
import fr.dreamin.dreamapi.api.DreamAPI;
import fr.dreamin.dreamapi.api.cmd.DreamCmd;
import fr.dreamin.dreamapi.api.gui.model.GuiInterface;
import fr.dreamin.dreamapi.api.gui.service.GuiService;
import fr.dreamin.dreamapi.core.gui.item.GuiItems;
import fr.dreamin.dreamapi.core.gui.visualizer.InventoryVisualizerHelper;
import fr.dreamin.dreamapi.core.item.builder.ItemBuilder;
import net.kyori.adventure.text.Component;
import org.bukkit.Material;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.jetbrains.annotations.NotNull;
import xyz.xenondevs.invui.gui.Gui;
import xyz.xenondevs.invui.inventory.VirtualInventory;
import xyz.xenondevs.invui.item.Item;
import xyz.xenondevs.invui.item.ItemProvider;

import java.util.UUID;
import java.util.function.Function;

@DreamCmd
public final class GUICmd {

  @CommandDescription("Open a GUI with a cursor visualizer")
  @CommandMethod("gui-test cursorhandler")
  @CommandPermission("test")
  private void cursorHandler(CommandSender sender) {
    if (!(sender instanceof Player player)) return;

    final Function<ItemStack, ItemProvider> visualizer = stack -> {
      if (stack == null) return null;
      return new ItemBuilder(stack.clone())
        .setName(Component.text("Cursor visualized"))
        .setEnchantGlint(true)
        .toGuiItem();
    };

    final var inventory = createDemoVirtualInventory();

    new VirtualInventoryDemoGUI("Inventory Visualizer Demo", "VirtualInventory slots should be visualized", inventory)
      .setCursorVisualizer(visualizer)
      .open(player);

  }

  @CommandDescription("Open a GUI with an open handler")
  @CommandMethod("gui-test openhandler")
  @CommandPermission("test")
  private void openHandler(CommandSender sender) {
    if (!(sender instanceof Player player)) return;

    new FeatureDemoGUI("Open Handler Demo", "A chat message is sent when the GUI opens")
      .addOpenHandler(() -> player.sendMessage(Component.text("[openHandler] GUI opened")))
      .open(player);
  }

  @CommandDescription("Open a GUI with a dynamic title supplier")
  @CommandMethod("gui-test titlesupplier")
  @CommandPermission("test")
  private void titleSupplier(CommandSender sender) {
    if (!(sender instanceof Player player)) return;

    player.sendMessage(Component.text("Re-run /gui-test titlesupplier to see a new generated title."));

    new FeatureDemoGUI("Title Supplier Demo", "Title is generated by setTitleSupplier")
      .setTitleSupplier(() -> Component.text("Dynamic title @ " + System.currentTimeMillis()))
      .open(player);
  }

  @CommandDescription("Open a GUI with an inventory visualizer")
  @CommandMethod("gui-test inventoryvisualizer")
  @CommandPermission("test")
  private void inventoryVisualizer(CommandSender sender) {
    if (!(sender instanceof Player player)) return;

    final Function<ItemStack, ItemProvider> visualizer = stack -> {
      if (stack == null) return null;
      return new ItemBuilder(stack.clone())
        .setName(Component.text("Inventory visualized"))
        .toGuiItem();
    };

    final var inventory = createDemoVirtualInventory();

    new VirtualInventoryDemoGUI("Inventory Visualizer Demo", "VirtualInventory slots should be visualized", inventory)
      .setInventoryVisualizer(visualizer)
      .open(player);
  }

  @CommandDescription("Open a practical visualizer test (cursor + inventory chain)")
  @CommandMethod("gui-test visualizertest")
  @CommandPermission("test")
  private void visualizerTest(CommandSender sender) {
    if (!(sender instanceof Player player)) return;

    final var inventoryVisualizer = InventoryVisualizerHelper.chainVisualizers(
      InventoryVisualizerHelper.emptyGlassPane(Material.LIGHT_GRAY_STAINED_GLASS_PANE),
      InventoryVisualizerHelper.glintVisualizer()
    );

    final var cursorVisualizer = InventoryVisualizerHelper.conditionalGlint(stack -> stack != null && !stack.isEmpty());

    player.sendMessage(Component.text("Visualizer test opened. Move an item on your cursor for cursor visualizer."));
    player.sendMessage(Component.text("Inventory visualizer applies on InventoryLink-based slots."));

    new FeatureDemoGUI("Visualizer Test", "Cursor is glinted, inventory visualizer is chained")
      .setCursorVisualizer(cursorVisualizer)
      .setInventoryVisualizer(inventoryVisualizer)
      .open(player);
  }

  @CommandDescription("Alias for inventory visualizer test")
  @CommandMethod("gui-test inventoryvisuyalizer")
  @CommandPermission("test")
  private void inventoryVisualizerAlias(CommandSender sender) {
    inventoryVisualizer(sender);
  }

  @CommandDescription("Open a GUI with outside click handlers")
  @CommandMethod("gui-test outsideclickhandlers")
  @CommandPermission("test")
  private void outsideClickHandlers(CommandSender sender) {
    if (!(sender instanceof Player player)) return;

    player.sendMessage(Component.text("Click outside the GUI to trigger the handler"));

    new FeatureDemoGUI("Outside Click Demo", "Outside click sends a chat message")
      .addOutsideClickHandler(event -> player.sendMessage(Component.text("[outsideClickHandler] Outside click detected (" + event.getClass().getSimpleName() + ")")))
      .open(player);
  }

  @CommandDescription("Open a 2-step GUI flow to test BACK + GuiService history")
  @CommandMethod("gui-test backservice")
  @CommandPermission("test")
  private void backService(CommandSender sender) {
    if (!(sender instanceof Player player)) return;

    sendGuiServiceState(player, "before-open-root");
    new BackServiceRootGUI(player.getUniqueId()).open(player);
  }

  private static void sendGuiServiceState(final @NotNull Player player, final @NotNull String context) {
    final GuiService guiService;
    try {
      guiService = DreamAPI.getAPI().getService(GuiService.class);
    } catch (Throwable throwable) {
      player.sendMessage(Component.text("[backService] GuiService unavailable in context: " + context));
      return;
    }

    final var current = guiService.getCurrentSession(player);
    final var previous = guiService.getPreviousGui(player);
    final var historySize = guiService.getHistory(player).size();

    final var currentLabel = current == null ? "none" : current.getGuiName();
    final var previousLabel = previous == null ? "none" : previous.getClass().getSimpleName();

    player.sendMessage(Component.text("[GuiService " + context + "] current=" + currentLabel + ", previous=" + previousLabel + ", history=" + historySize));
  }

  private static @NotNull VirtualInventory createDemoVirtualInventory() {
    final ItemStack[] items = new ItemStack[18];
    items[0] = new ItemStack(Material.DIAMOND, 3);
    items[1] = new ItemStack(Material.GOLD_INGOT, 12);
    items[2] = new ItemStack(Material.EMERALD, 7);
    items[9] = new ItemStack(Material.BREAD, 5);
    items[10] = new ItemStack(Material.IRON_INGOT, 16);
    return new VirtualInventory(items);
  }

  private static final class FeatureDemoGUI extends GuiInterface {

    private final @NotNull String title;
    private final @NotNull String subtitle;

    private FeatureDemoGUI(final @NotNull String title, final @NotNull String subtitle) {
      this.title = title;
      this.subtitle = subtitle;
    }

    @Override
    public Component name(final @NotNull Player player) {
      return Component.text(title);
    }

    @Override
    public Gui guiUpper(final @NotNull Player player) {
      return Gui.builder()
        .setStructure(
          ". . . . . . . . .",
          ". . . . . . . . .",
          ". . . . . . . . .",
          ". . . . I . . . .",
          ". . . . . . . . .",
          ". . . . . . . . ."
        )
        .addIngredient('I', Item.builder()
          .setItemProvider(new ItemBuilder(Material.BOOK)
            .setName(Component.text(title))
            .setLore(Component.text(subtitle))
            .toGuiItem())
          .addClickHandler((clickedItem, click) -> click.player().sendMessage(Component.text("Demo item clicked (" + clickedItem.getClass().getSimpleName() + ")")))
          .build())
        .build();
    }
  }

  private static final class VirtualInventoryDemoGUI extends GuiInterface {

    private final @NotNull String title;
    private final @NotNull String subtitle;
    private final @NotNull VirtualInventory inventory;

    private VirtualInventoryDemoGUI(
      final @NotNull String title,
      final @NotNull String subtitle,
      final @NotNull VirtualInventory inventory
    ) {
      this.title = title;
      this.subtitle = subtitle;
      this.inventory = inventory;
    }

    @Override
    public Component name(final @NotNull Player player) {
      return Component.text(title);
    }

    @Override
    public Gui guiUpper(final @NotNull Player player) {
      final var gui = Gui.builder()
        .setStructure(
          "V V V V V V V V V",
          "V V V V V V V V V",
          ". . . . . . . . .",
          ". . . . I . . . .",
          ". . . . . . . . .",
          ". . . . . . . . ."
        )
        .addIngredient('I', Item.builder()
          .setItemProvider(new ItemBuilder(Material.BOOK)
            .setName(Component.text(title))
            .setLore(Component.text(subtitle))
            .toGuiItem())
          .build())
        .build();

      gui.setInventory('V', this.inventory, new ItemBuilder(Material.GRAY_STAINED_GLASS_PANE).setHideToolType(true).toGuiItem());
      return gui;
    }
  }

  private static final class BackServiceRootGUI extends GuiInterface {

    private final @NotNull UUID playerId;

    private BackServiceRootGUI(final @NotNull UUID playerId) {
      this.playerId = playerId;
    }

    @Override
    public Component name(final @NotNull Player player) {
      return Component.text("Back Service Root");
    }

    @Override
    public Gui guiUpper(final @NotNull Player player) {
      return Gui.builder()
        .setStructure(
          ". . . . . . . . .",
          ". . . . . . . . .",
          ". . . . . . . . .",
          ". . . . N . . . .",
          ". . . . S . . . .",
          ". . . . . . . . ."
        )
        .addIngredient('N', Item.builder()
          .setItemProvider(new ItemBuilder(Material.EMERALD)
            .setName(Component.text("Open child GUI"))
            .toGuiItem())
          .addClickHandler((item, click) -> {
            sendGuiServiceState(click.player(), "root-before-child");
            new BackServiceChildGUI(playerId).open(click.player());
          })
          .build())
        .addIngredient('S', Item.builder()
          .setItemProvider(new ItemBuilder(Material.BOOK)
            .setName(Component.text("Show GuiService state"))
            .toGuiItem())
          .addClickHandler((item, click) -> sendGuiServiceState(click.player(), "root-state"))
          .build())
        .build();
    }
  }

  private static final class BackServiceChildGUI extends GuiInterface {

    private final @NotNull UUID playerId;

    private BackServiceChildGUI(final @NotNull UUID playerId) {
      this.playerId = playerId;
    }

    @Override
    public Component name(final @NotNull Player player) {
      return Component.text("Back Service Child");
    }

    @Override
    public Gui guiUpper(final @NotNull Player player) {
      return Gui.builder()
        .setStructure(
          ". . . . . . . . .",
          ". . . . . . . . .",
          ". . . . . . . . .",
          ". . . B . . . . .",
          ". . . S . . . . .",
          ". . . . . . . . ."
        )
        .addIngredient('B', GuiItems.BACK(playerId, Material.OAK_DOOR, null, true).build())
        .addIngredient('S', Item.builder()
          .setItemProvider(new ItemBuilder(Material.BOOK)
            .setName(Component.text("Show GuiService state"))
            .toGuiItem())
          .addClickHandler((item, click) -> sendGuiServiceState(click.player(), "child-state"))
          .build())
        .build();
    }
  }

}
