

def nettyVersion = "4.1.68.Final"
def modelEngineVersion = "R4.1.0"

repositories {
  mavenCentral()
  maven { url = 'https://mvn.lumine.io/repository/maven-public/' }
}

dependencies {
  api("com.fasterxml.jackson.core:jackson-databind:2.19.1")

  compileOnly("com.ticxo.modelengine:ModelEngine:$modelEngineVersion")

  compileOnly "io.netty:netty-all:$nettyVersion"
}

base {
  archivesName.set("dreamapi-api")
}